[package]
name = "dahl-salso"
version = "0.1.0"
authors = ["David B. Dahl <dahl@stat.byu.edu>"]
edition = "2018"
description = "An implement of the sequentially-allocated latent structure optimization (SALSO) to find a partition that minimizes various loss functions. The SALSO method was presented at the workshop 'Bayesian Nonparametric Inference: Dependence Structures and their Applications' in Oaxaca, Mexico on December 6, 2017."
homepage = "https://dahl.byu.edu"
license = "MIT OR Apache-2.0"

[dependencies]
dahl-partition = { git="https://dahl-git.byu.edu/dahl/rust-dahl-partition.git" }
rand = "0.7.0"
crossbeam = "0.7.2"
num_cpus = "1.10.1"
approx = "0.3.2"
